# Generated by Django 3.1.5 on 2021-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='evidence_image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
